/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as dataSharingSol from "./DataSharing.sol";
export type { dataSharingSol };
import type * as core from "./core";
export type { core };
