/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as tokenTestNativeSol from "./TokenTestNative.sol";
export type { tokenTestNativeSol };
export type { AssetContract } from "./AssetContract";
